[server]
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
serverAddress = "localhost"
serverPort = 8501

[theme]
base = "dark"
primaryColor = "#9f7aea"
backgroundColor = "#1a1a1a"
secondaryBackgroundColor = "#2d2d2d"
textColor = "#f0f0f0"
font = "sans serif"
